### ISSUE TITLE
USER STORY: User page and attended events

### ISSUE THREAD

**Issue by Emese92** [Emese92/My-first-Agile-Project#5]
As a **user** I can **mark which event will I attend** so that **could be tracked back on a user's page.**

## Acceptance Criteria

- Acceptance Criteria 1: The weekly events would be clickable
- Acceptance Criteria 2: A user's page should be added
- Acceptance Criteria 3: The event could be marked as "attend" or "attended"

## Tasks
- [ ] Update the events as clickables
- [ ] Create a popup window with "attend" and "ignore" options
- [ ] Create a user's page where the attended events are listed
